[tool.pytest.ini_options]
pythonpath = [
  ".", "src",  # Указываем для Pytest, где находится приложение
]

markers = [
    "token: тесты для проверки токена в header запроса",
    "user: тесты для проверки вывода данных о пользователе",
    "tweet: тесты для проверки создания, вывода и удаления твитов",
    "like: тесты для проверки создания и удаления лайков",
    "follower: тесты для проверки создания и удаления подписок между пользователями",
    "image: тесты для проверки загрузки изображений к твитам",
]


# Игнорировать предупреждения DeprecationWarning
filterwarnings = [
    "ignore::DeprecationWarning",
]

# Асинхронные функции будут распознаваться Pytest и нормально отрабатываться
asyncio_mode="auto"

# Строгий режим
# При нем фикстуры пришлось бы определять через - @pytest_asyncio.fixture
# asyncio_mode="strict"
