[tool.pytest.ini_options]
pythonpath = [
  ".", "src",  # Указываем для Pytest, где находится приложение
]

# Кастомные маркеры для быстрого запуска тестов нужной категории, н-р: pytest -v -m token
markers = [
    "token: тесты для проверки токена в header запроса",
    "user: тесты для проверки вывода данных о пользователе",
    "tweet: тесты для проверки создания, вывода и удаления твитов",
    "like: тесты для проверки создания и удаления лайков",
    "follower: тесты для проверки создания и удаления подписок между пользователями",
    "image: тесты для проверки загрузки изображений к твитам",
]


# Игнорировать предупреждения DeprecationWarning
filterwarnings = [
    "ignore::DeprecationWarning",
]

# Для нормальной отработки асинхронных функций Pytest
asyncio_mode="auto"
