"""Added data

Revision ID: a61d9db18ca6
Revises: 61c7e2db0e92
Create Date: 2023-09-17 11:07:22.395428

"""
from typing import Sequence, Union
from alembic import op
from sqlalchemy import Integer, String, column, table


# revision identifiers, used by Alembic.
revision: str = 'a61d9db18ca6'
down_revision: Union[str, None] = 'fa7f8eb2e545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Пользователя
    # Определяем таблицу и колонки для добавления данных
    users_table = table("users", column("username", String), column("api_key", String))

    # Добавляем данные
    op.bulk_insert(
        users_table,
        [
            {"username": "Дима", "api_key": "user1"},
            {"username": "Ленчик", "api_key": "user2"},
            {"username": "Кристина", "api_key": "user3"},
            {"username": "Валера", "api_key": "user4"},
        ],
    )

    # Подписки на пользователей
    users_to_users_table = table(
        "user_to_user", column("followers_id", Integer), column("following_id", Integer)
    )

    op.bulk_insert(
        users_to_users_table,
        [
            {"followers_id": 1, "following_id": 2},
            {"followers_id": 1, "following_id": 3},
            {"followers_id": 2, "following_id": 1},
            {"followers_id": 3, "following_id": 1},
            {"followers_id": 3, "following_id": 2},
            {"followers_id": 4, "following_id": 3},
        ],
    )

    # Твиты
    tweets_table = table("tweets", column("tweet_data", String), column("user_id", Integer))

    op.bulk_insert(
        tweets_table,
        [
            {"tweet_data": "Всем привет, я Дмитрий", "user_id": 1},
            {"tweet_data": "Добрый день, меня зовут Елена", "user_id": 2},
            {"tweet_data": "Я Кристина, здравствуйте", "user_id": 3},
            {"tweet_data": "Валера, к вашим услугам!", "user_id": 4},
            {"tweet_data": "Приятно познакомиться...", "user_id": 1},
            {"tweet_data": "Это очень интересный проект", "user_id": 2},
            {"tweet_data": "Я сегодня сходила в зал", "user_id": 3},
            {"tweet_data": "Пришел в гости, а там никого!", "user_id": 4},
        ],
    )

    # Изображения к твитам
    images_table = table(
        "images", column("tweet_id", Integer), column("path_media", String),
    )

    op.bulk_insert(
        images_table,
        [
            {"tweet_id": 1, "path_media": "images/tweets/2023/9/17/avatar.jpg"},
            {"tweet_id": 1, "path_media": "images/tweets/2023/9/17/Screen1.png"},
            {"tweet_id": 2, "path_media": "images/tweets/2023/9/17/avatar.jpg"},
            {"tweet_id": 3, "path_media": "images/tweets/2023/9/17/Screen1.png"},
            {"tweet_id": 4, "path_media": "images/tweets/2023/9/17/avatar.jpg"},
            {"tweet_id": 5, "path_media": "images/tweets/2023/9/17/Screen2.png"},
            {"tweet_id": 5, "path_media": "images/tweets/2023/9/17/avatar.jpg"},
            {"tweet_id": 6, "path_media": "images/tweets/2023/9/17/Screen2.png"},
        ],
    )

    # Лайки
    likes_table = table(
        "likes", column("user_id", Integer), column("tweets_id", Integer)
    )

    op.bulk_insert(
        likes_table,
        [
            {"user_id": 1, "tweets_id": 2},
            {"user_id": 1, "tweets_id": 5},
            {"user_id": 2, "tweets_id": 2},
            {"user_id": 2, "tweets_id": 1},
            {"user_id": 3, "tweets_id": 3},
            {"user_id": 3, "tweets_id": 6},
            {"user_id": 3, "tweets_id": 8},
            {"user_id": 4, "tweets_id": 4},
            {"user_id": 4, "tweets_id": 3},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
